name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, develop]

jobs:
    check-lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '12'
            - name: Install Dependencies
              run: |
                  npm install
            - name: Lint
              run: |
                  npm run lint

    check-e2e-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '12'
            - name: Install Dependencies
              run: |
                  npm install
            - name: Tests
              run: |
                  npm install
                  npm run test:e2e

    check-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '12'
            - name: Install Dependencies
              run: |
                  npm install
            - name: Tests
              run: |
                  npm install
                  npm run test
